{
 "title": "ik-paip-data-collector-IK Data collector",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Статусы обработки сообщений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(result) (increase(collector_processor_result_total{application=\"ik-paip-data-collector\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер очереди на обработку",
   "type": "timeseries",
   "description": "Очередь данных в Redis",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(source_queue{application=\"ik-paip-data-collector\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общий размер очереди на обработку",
   "type": "timeseries",
   "description": "Данные, ожидающие запись в отчётную БД",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(type) (source{application=\"ik-paip-data-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}