annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/grafana
apiVersion: v2
appVersion: 10.3.3
description: The leading tool for querying and visualizing time series and metrics.
keywords:
- monitoring
- metric
kubeVersion: ^1.8.0-0
maintainers:
- email: zalupa@gmail.com
  name: nikitaevdokimov
name: grafana
type: application
version: 7.3.3
