{
 "title": "[PROD] Operate",
 "time": { "from": "2023-12-11T04:05:37.000Z", "to": "2023-12-12T07:17:50.000Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(operate_events_processed_total, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(operate_events_processed_total{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(operate_events_processed_total{namespace=~\"$namespace\", pod=~\"$pod\"}, partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Exported and processed Zeebe records rate per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operate_events_processed_total{namespace=~\"$namespace\", pod=~\"$pod\", partition=~\"$partition\"}[10m])) by (status)",
     "legendFormat": "processed ({{status}})"
    },
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\", valueType=~\"JOB|PROCESS_INSTANCE|VARIABLE|VARIABLE_DOCUMENT|DEPLOYMENT\",action=~\"exported\",partition=~\"$partition\"}[10m]))",
     "legendFormat": "exported"
    }
   ]
  },
  {
   "title": "Import latencies, 10 min average, sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(operate_import_query_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])/rate(operate_import_query_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])>0)",
     "legendFormat": "Importer read latency"
    },
    {
     "expr": "avg(rate(operate_import_index_query_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])/rate(operate_import_index_query_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])>0)",
     "legendFormat": "Importer index latency"
    }
   ]
  },
  {
   "title": "Finished instances archiving rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operate_archived_process_instances_total{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])) by (pod)",
     "legendFormat": "{{pod}}: archived"
    },
    {
     "expr": "sum(rate(operate_events_processed_finished_process_instances_total{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])) by (pod)",
     "legendFormat": "{{pod}}: finished"
    }
   ]
  },
  {
   "title": "Archiver latencies, 10 min average, sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(operate_archiver_query_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])/rate(operate_archiver_query_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[10m]))",
     "legendFormat": "Archiver read latency"
    },
    {
     "expr": "avg(rate(operate_archiver_reindex_query_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])/rate(operate_archiver_reindex_query_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[10m]))",
     "legendFormat": "Archiver reindex latency"
    },
    {
     "expr": "avg(rate(operate_archiver_delete_query_seconds_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[10m])/rate(operate_archiver_delete_query_seconds_count{namespace=~\"$namespace\", pod=~\"$pod\"}[10m]))",
     "legendFormat": "Archiver delete latency"
    }
   ]
  },
  {
   "title": "Processed event rate per event type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operate_events_processed_total{namespace=~\"$namespace\", pod=~\"$pod\", status=\"succeeded\",partition=~\"$partition\"}[10m])) by (type)",
     "legendFormat": " {{type}} (processed)"
    },
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\", pod=~\"$pod\", valueType=~\"JOB|PROCESS_INSTANCE|VARIABLE|DEPLOYMENT\",action=\"exported\",partition=~\"$partition\"}[10m])) by (valueType)",
     "legendFormat": "{{valueType}} (exported)"
    }
   ]
  },
  {
   "title": "Number of records per type",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(operate_events_processed_total{namespace=~\"$namespace\", pod=~\"$pod\", status=\"succeeded\",partition=~\"$partition\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}