{
 "title": "ArangoDB Synchronization",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "target",
    "query": {
     "query": "query_result(synchronization_status_running)"
    }
   },
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synchronization_status_running{target=\"$target\"}",
     "legendFormat": "status"
    },
    {
     "expr": "synchronization_status_phase{target=\"$target\"}",
     "legendFormat": "phase"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synchronization_status_progressFailedConnects{target=\"$target\"}",
     "legendFormat": "Progress Failed Connects"
    },
    {
     "expr": "synchronization_status_totalFailedConnects{target=\"$target\"}",
     "legendFormat": "Total Failed Connects"
    },
    {
     "expr": "synchronization_status_lastErrorErrorNum{target=\"$target\"}",
     "legendFormat": "Last Error ErrorNum"
    },
    {
     "expr": "synchronization_status_totalResyncs{target=\"$target\"}",
     "legendFormat": "Total Resyncs"
    }
   ]
  },
  {
   "title": "Average Fetch/Apply  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "synchronization_status_averageFetchTime{target=\"$target\"}",
     "legendFormat": "Average Fetch Time"
    },
    {
     "expr": "synchronization_status_averageApplyTime{target=\"$target\"}",
     "legendFormat": "Average Apply Time"
    }
   ]
  },
  {
   "title": "Ticks Behind",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "synchronization_status_ticksBehind{target=\"$target\"}",
     "legendFormat": "Ticks Behind"
    }
   ]
  },
  {
   "title": "ContinuousTick",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "synchronization_status_lastAvailableContinuousTick{target=\"$target\"} -synchronization_status_lastAppliedContinuousTick{target=\"$target\"}",
     "legendFormat": "Availabl - Applied"
    },
    {
     "expr": "synchronization_status_lastAvailableContinuousTick{target=\"$target\"} - synchronization_status_lastProcessedContinuousTick{target=\"$target\"}",
     "legendFormat": "Availabl - Processed"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"arangodb\", pod=~\".*$target.*\"} |~\"ERROR\"[10s]))"
    }
   ]
  },
  {
   "title": "errorMessage",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{namespace=\"arangodb\", pod=~\".*$target.*\"} |~\"ERROR\""
    }
   ]
  }
 ]
}