{
 "title": "ArangoDB Overview",
 "description": "ArangoDB kubernetes dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Process Memory Set Size Percent",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_resident_set_size_percent{} *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Idle Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "arangodb_server_statistics_idle_percent",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_virtual_memory_size",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RocksDB sst file size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rocksdb_live_sst_files_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Agency write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(arangodb_agent_write_ok[15s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RocksDB cache access rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(rocksdb_block_cache_usage[15s])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}