annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
apiVersion: v2
appVersion: 2.10.1
description: Install kube-state-metrics to generate and expose cluster-level metrics
keywords:
- metric
- monitoring
- prometheus
- kubernetes
maintainers:
- email: zalupa@gmail.com
  name: nikitaevdokimov
name: kube-state-metrics
type: application
version: 5.16.4
