{
 "title": "[PROD] Registry (registry-commissionmember)",
 "description": "Dashboard for Registry (registry-commissionmember)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" },
   { "name": "registryName", "label": "Registry Service Name", "query": "registry-commissionmember" },
   {
    "name": "instance",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$registryName\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "probe_success{task=\"availability\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Infrastructure Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Health Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "min_over_time(probe_success{task=\"availability\", namespace=~\"$namespace\", name=~\"$registryName\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Infra Health Status ",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "min_over_time(registry_infrastructure_fail{application=~\"$registryName\", namespace=~\"$namespace\"}[1m])",
     "legendFormat": "{{infra}}"
    }
   ]
  },
  {
   "title": "Registry Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Operation\\Sec",
   "type": "graph",
   "description": "Any successful operation.",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(rate(registry_traversal_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fatal Failed Operations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\", code!~\"400|401|403|404|422\"}) by (code, schema)",
     "legendFormat": "Code {{code}} - {{schema}}"
    }
   ]
  },
  {
   "title": "Latency per Operation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_storage_operation_execution_seconds_sum{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation) / sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Latency per Traversal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_traversal_execution_seconds_sum{application=\"$registryName\", instance=~\"$instance\"}[3m])) by (type) / sum(rate(registry_traversal_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[3m])) by (type)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Documents per Operation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(registry_storage_documents_processed_total{application=\"$registryName\", instance=~\"$instance\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Storage Operation Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read Operation-by-Schema\\Sec",
     "type": "graph",
     "description": "Only for successful operations",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\", operation=~\"exist|count|find|search|paging\"}[1m])) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Modify Operation-by-Schema\\Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\", operation=~\"create|update|save|unlink|delete|delete_hide\"}[1m])) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Validation Status per Schema",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 5, "x": 0, "y": 44 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(registry_validation_total{application=\"$registryName\", status=~\"fail|excluded\"}) by (status, schema)",
       "legendFormat": "{{status}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Failed Operation-by-Schema\\Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 7, "x": 5, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\"}[1m])) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Failed Critical Operation-by-Schema",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 5, "x": 12, "y": 44 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\", code!~\"400|401|403|404|422\"}) by (operation, code, schema)",
       "legendFormat": "Code {{code}} - {{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Failed All Operation-by-Schema",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 44 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\"}) by (schema, operation, code)",
       "legendFormat": "Code {{code}} - {{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Schema Documents Processed per Operation",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(registry_storage_documents_processed_total{application=\"$registryName\", instance=~\"$instance\"}) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Latency Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Latency per Operation",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_sum{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation) / sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Latency per Operation-by-Schema",
     "type": "stat",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_sum{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[2m])) by (schema, operation) / sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[2m])) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Traversal Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Registry Traversal per Type",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_traversal_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Registry Traversal per Type and Collection",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_traversal_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[1m])) by (type, collection)",
       "legendFormat": "{{type}} - {{collection}}"
      }
     ]
    },
    {
     "title": "Latency per Traversal",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(registry_traversal_execution_seconds_sum{application=\"$registryName\", instance=~\"$instance\"}[3m])) by (type) / sum(rate(registry_traversal_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[3m])) by (type)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Latency per Traversal per Collection",
     "type": "stat",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(registry_traversal_execution_seconds_sum{application=\"$registryName\", instance=~\"$instance\"}[3m])) by (type, collection) / sum(rate(registry_traversal_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[3m])) by (type, collection)",
       "legendFormat": "{{type}} - {{collection}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kafka Operation\\Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_kafka_consumer_operation_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[1m])) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Kafka Failed Operation-by-Schema\\Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_operation_execution{application=\"$registryName\", status=\"fail\", instance=~\"$instance\"}[1m])) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Kafka Documents Processed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(registry_kafka_consumer_documents_processed_total{application=\"$registryName\", instance=~\"$instance\"}) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Http Method-per-Status\\Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[1m])) by (method, status)",
       "legendFormat": "{{method}} - {{status}}"
      }
     ]
    },
    {
     "title": "Http Latency per Method-per-Uri",
     "type": "stat",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$registryName\", instance=~\"$instance\"}[2m])) by (method, uri) / sum(rate(http_server_requests_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[2m])) by (method, uri)",
       "legendFormat": "{{method}} - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{application=\"$registryName\", instance=~\"$instance\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$registryName\", instance=~\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$registryName\", instance=~\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$registryName\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{application=\"$registryName\", instance=~\"$instance\"} or jvm_threads_live_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{application=\"$registryName\", instance=~\"$instance\"} or jvm_threads_daemon_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{application=\"$registryName\", instance=~\"$instance\"} or jvm_threads_peak_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}