---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-demo
  template:
    metadata:
      labels:
        app: nextjs-demo
    spec:
      containers:
        - name: nextjs-demo
          image: nextjs-demo:1.0.1
          ports:
            - containerPort: 3000
