{
 "title": "HTTP and POOLS (Micrometer)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" },
   { "name": "INSTANCE_REGX", "label": "INSTANCE_REGX", "query": { "query": "label_values(instance)" } },
   {
    "name": "JOB",
    "label": "JOB",
    "query": {
     "query": "label_values({instance=~\"$INSTANCE_REGX\"},job)"
    }
   },
   {
    "name": "INSTANCE",
    "label": "INSTANCE",
    "query": {
     "query": "label_values({job=~\"$JOB\"},instance)"
    }
   },
   {
    "name": "POD",
    "label": "POD",
    "query": {
     "query": "label_values({instance=~\"$INSTANCE\"},pod)"
    }
   },
   {
    "name": "URI",
    "label": "URI",
    "query": {
     "query": "label_values({instance=\"$INSTANCE\"},uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP - Среднее время выполнения запросов",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (instance, status, uri, method) (rate(http_server_requests_seconds_sum{instance=\"$INSTANCE\", job=\"$JOB\", uri=~\"$URI\"} [60s])))/(sum by (instance, status, uri, method) (rate(http_server_requests_seconds_count{instance=\"$INSTANCE\", job=\"$JOB\", uri=~\"$URI\"} [60s])))",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP - Количество запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$INSTANCE\", job=\"$JOB\", uri=~\"$URI\"}[60s])) by (instance, job, status, uri, method)",
     "legendFormat": "{{status}} {{method}} {{uri}}"
    }
   ]
  },
  { "title": "EXECUTOR POOL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Executor pool - потоки исполнения",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "executor_pool_core_threads{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "executor_pool_size_threads{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "executor_active_threads{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "executor_pool_max_threads{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    }
   ]
  },
  {
   "title": "Executor queue - очередь задач",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "executor_queued_tasks{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "executor_queue_remaining_tasks{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    }
   ]
  },
  {
   "title": "Executor time - время исполнения задачи",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "executor_seconds_max{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    }
   ]
  },
  { "title": "HIKARI POOL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Hikari pool - потоки взаимодействия с БД",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hikaricp_connections_max{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hikaricp_connections_min{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hikaricp_connections_idle{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hikaricp_connections{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hikaricp_connections_active{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hikaricp_connections_pending{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Hikari time - время",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_max{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "hikaricp_connections_creation_seconds_max{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "hikaricp_connections_usage_seconds_max{job=\"$JOB\", instance=\"$INSTANCE\"}",
     "legendFormat": "{{__name__}} {{name}}"
    }
   ]
  }
 ]
}