{
 "title": "[PROD] Registry (micro-registry-journal)",
 "description": "Dashboard for Registry (micro-registry-journal)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" },
   { "name": "registryName", "label": "Registry Service Name", "query": "micro-registry-journal" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$registryName\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Infrastructure Health Statistic",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(registry_infrastructure_fail{application=\"$registryName\"}) by (infra)",
       "legendFormat": "{{infra}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Operation\\Sec",
   "type": "graph",
   "description": "Any successful operation.",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Failed Critical Operations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\", code!~\"400|401|403|404|422\"}) by (code, schema)",
     "legendFormat": "Code {{code}} - {{schema}}"
    }
   ]
  },
  {
   "title": "Latency per Operation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_storage_operation_execution_seconds_sum{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation) / sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Documents per Operation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(registry_storage_documents_processed_total{application=\"$registryName\", instance=~\"$instance\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Storage Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read Operation-by-Schema\\Sec",
     "type": "graph",
     "description": "Only for successful operations",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\", operation=~\"exist|count|find|search|paging\"}[1m])) by (schema, operation)",
       "legendFormat": "{{schema}} - {{operation}}"
      }
     ]
    },
    {
     "title": "Failed Operation-by-Schema\\Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\"}[1m])) by (schema, operation)",
       "legendFormat": "{{schema}} - {{operation}}"
      }
     ]
    },
    {
     "title": "Latency per Operation",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_sum{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation) / sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[3m])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Modify Operation-by-Schema\\Sec",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\", operation=~\"create|update|save|unlink|delete|delete_hide\"}[1m])) by (schema, operation)",
       "legendFormat": "{{schema}} - {{operation}}"
      }
     ]
    },
    {
     "title": "Failed Critical Operation-by-Schema",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 5, "x": 12, "y": 47 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\", code!~\"400|401|403|404|422\"}) by (operation, code, schema)",
       "legendFormat": "Code {{code}} - {{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Failed All Operation-by-Schema",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 47 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"fail\", instance=~\"$instance\"}) by (schema, operation, code)",
       "legendFormat": "Code {{code}} - {{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Schema Documents Processed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(registry_storage_documents_processed_total{application=\"$registryName\", instance=~\"$instance\"}) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    },
    {
     "title": "Latency per Operation-by-Schema",
     "type": "stat",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(registry_storage_operation_execution_seconds_sum{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[2m])) by (schema, operation) / sum(rate(registry_storage_operation_execution_seconds_count{application=\"$registryName\", status=\"success\", instance=~\"$instance\"}[2m])) by (schema, operation)",
       "legendFormat": "{{operation}} - {{schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kafka Operation\\Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(registry_kafka_consumer_operation_execution_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[1m])) by (schema, operation)",
       "legendFormat": "{{schema}} -- {{operation}}"
      }
     ]
    },
    {
     "title": "Kafka Failed Operation-by-Schema\\Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_operation_execution{application=\"$registryName\", status=\"fail\", instance=~\"$instance\"}[1m])) by (schema, operation)",
       "legendFormat": "{{schema}} - {{operation}}"
      }
     ]
    },
    {
     "title": "Kafka Documents Processed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(registry_kafka_consumer_documents_processed_total{application=\"$registryName\", instance=~\"$instance\"}) by (schema, operation)",
       "legendFormat": "{{schema}} - {{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Http Method-per-Status\\Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[1m])) by (method, status)",
       "legendFormat": "{{method}} - {{status}}"
      }
     ]
    },
    {
     "title": "Http Latency per Method-per-Uri",
     "type": "stat",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$registryName\", instance=~\"$instance\"}[2m])) by (method, uri) / sum(rate(http_server_requests_seconds_count{application=\"$registryName\", instance=~\"$instance\"}[2m])) by (method, uri)",
       "legendFormat": "{{method}} - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "process"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{application=\"$registryName\", instance=~\"$instance\"}[1h])",
       "legendFormat": "process-1h"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$registryName\", instance=~\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$registryName\", instance=~\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$registryName\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{application=\"$registryName\", instance=~\"$instance\"} or jvm_threads_live_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon{application=\"$registryName\", instance=~\"$instance\"} or jvm_threads_daemon_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak{application=\"$registryName\", instance=~\"$instance\"} or jvm_threads_peak_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{application=\"$registryName\", instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}