{
 "title": "Strimzi Kafka Custom",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kafka_server_replicamanager_leadercount)"
    }
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(kafka_server_replicamanager_leadercount{namespace=\"$kubernetes_namespace\"})"
    }
   },
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": {
     "query": "query_result(kafka_server_replicamanager_leadercount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": {
     "query": "query_result(kafka_cluster_partition_replicascount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"})"
    }
   },
   {
    "name": "kafka_partition",
    "label": "Partition",
    "query": {
     "query": "query_result(kafka_log_log_size{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",topic=~\"$kafka_topic\"})"
    }
   },
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of brokers online",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_controller_controllerstats_uncleanleaderelections_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "stat",
   "description": "Replicas that are online",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Partitions at minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Partitions under minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ISR Expands",
   "type": "timeseries",
   "description": "Expanding InSync Replicas count\n(if changes it's bad)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrexpands_total{namespace=\"$kubernetes_namespace\",pod=~\"$strimzi_cluster_name-$kafka_broker\",container=\"kafka\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ISR Shrinks",
   "type": "timeseries",
   "description": "Shriking of InSync Replicas count \n(changing is bad)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrshrinks_total{namespace=\"$kubernetes_namespace\",pod=~\"$strimzi_cluster_name-$kafka_broker\",container=\"kafka\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate and Time",
   "type": "timeseries",
   "description": "Leader Election Rate and Time for different quantiles",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_controller_controllerstats_leaderelectionrateandtimems{namespace=\"$kubernetes_namespace\",pod=~\"$strimzi_cluster_name-$kafka_broker\",container=\"kafka\"}",
     "legendFormat": "{{pod}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Open File Descriptors",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",container=\"kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Zookeeper InSync Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeepersyncconnects_total{namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",strimzi_io_name=\"$strimzi_cluster_name-kafka\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Zookeeper Disconnected Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperdisconnects_total{namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",strimzi_io_name=\"$strimzi_cluster_name-kafka\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Zookeeper Connections Expired",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperexpires_total{namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",strimzi_io_name=\"$strimzi_cluster_name-kafka\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Zookeeper Connection is ReadOnly",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperreadonlyconnects_total{namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",strimzi_io_name=\"$strimzi_cluster_name-kafka\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Errors Rate",
   "type": "timeseries",
   "description": "Byte rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_errors_total{namespace=\"$kubernetes_namespace\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",strimzi_io_name=\"$strimzi_cluster_name-kafka\",error!=\"NONE\", error!=\"TOPIC_ALREADY_EXISTS\"}[1m])>0",
     "legendFormat": "{{pod}}-{{request}}-{{error}}"
    }
   ]
  },
  {
   "title": "Response Time Change Rate",
   "type": "timeseries",
   "description": "rate of changing total response time",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"} >0",
     "legendFormat": "{{pod}}-{{request}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "timeseries",
   "description": "Average percentage of time network processor is idle",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kafka_network_socketserver_networkprocessoravgidle_percent{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}*100) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Incoming Messages Rate"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "description": "Disk writes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_kafkaserver_linux_disk_write_bytes{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "timeseries",
   "description": "Fetch request rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "  sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "timeseries",
   "description": "Average percentage of time request handler threads are idle",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}*100) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "description": "Disk reads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_kafkaserver_linux_disk_read_bytes{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Connection Count per Listener",
   "type": "timeseries",
   "description": "Disk reads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socket_server_metrics_connection_count{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}) by (kubernetes_pod_name, listener)",
     "legendFormat": "{{listener}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_log_log_size{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",topic=~\"$kafka_topic\",partition=~\"$kafka_partition\"}",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  }
 ]
}