{
 "title": "Логирование (Loki)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ошибки в логах об отсутствии свободного места",
   "type": "timeseries",
   "description": "no space left on device",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "stdvar(rate({namespace=\"monitoring\"} |= `no space left on device` [5m]))",
     "legendFormat": "monitoring"
    },
    {
     "expr": "stdvar(rate({namespace=\"apps\"} |= `no space left on device` [5m]))"
    },
    {
     "expr": "stdvar(rate({namespace=\"arangodb\"} |= `no space left on device` [5m]))",
     "legendFormat": "arangodb"
    },
    {
     "expr": "stdvar(rate({namespace=\"argocd\"} |= `no space left on device` [5m]))",
     "legendFormat": "argocd"
    },
    {
     "expr": "stdvar(rate({namespace=\"kafka\"} |= `no space left on device` [5m]))",
     "legendFormat": "kafka"
    },
    {
     "expr": "stdvar(rate({namespace=\"mongodb\"} |= `no space left on device` [5m]))",
     "legendFormat": "mongodb"
    },
    {
     "expr": "stdvar(rate({namespace=\"longhorn-system\"} |= `no space left on device` [5m]))",
     "legendFormat": "longhorn"
    }
   ]
  },
  {
   "title": "Количество ошибок в логах apps и arangodb",
   "type": "timeseries",
   "description": "Количество ошибок в логах namespace apps и arangodb с разбивкой на пятиминутные интервалы.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "count(rate({namespace=\"apps\"} |~ `.*error.*|.*failed.*|.*exception.*|.*critical.*|.*failure.*` != `errors=null` != `INFO` != `errorsCount=null` [5m]))",
     "legendFormat": "apps"
    },
    {
     "expr": "count(rate({namespace=\"arangodb\"} |~ `.*error.*|.*failed.*|.*exception.*|.*critical.*|.*failure.*` != `INFO` != `errors=null` [5m]))",
     "legendFormat": "arangodb"
    }
   ]
  },
  {
   "title": "ERR в тексте логов (namespaces arangodb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(rate({namespace=\"arangodb\"} |= `ERR` [1m]))"
    }
   ]
  },
  {
   "title": "ERROR в тексте логов (apps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "count(rate({app=\"micro-registry-incident\"} |= `ERROR` [5m]))"
    }
   ]
  },
  {
   "title": "error в тексте логов (namespaces arangodb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(rate({namespace=\"arangodb\"} |= `error` [5m]))"
    }
   ]
  },
  {
   "title": "error в тексте логов (apps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "count(rate({namespace=\"arangodb\"} |= `error` [5m]))"
    }
   ]
  }
 ]
}