{
 "title": "[PROD] ArangoDB 3.9 mini",
 "time": { "from": "2023-12-07T19:25:56.986Z", "to": "2023-12-08T21:23:11.300Z" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "query_result(arangodb_connection_pool_connections_created_total{service=~\"$service\", namespace=\"arangodb\"})"
    }
   },
   {
    "name": "volume",
    "label": "DiskVolume",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"arangodb\"}, persistentvolumeclaim)"
    }
   },
   {
    "name": "pod_cpu",
    "label": "Pod(CPU)",
    "query": {
     "query": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"arangodb\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation (from limits)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"arangodb\",pod=~\"$pod_cpu\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"arangodb\",pod=~\"$pod_cpu\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (\r\n(\r\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"arangodb\", persistentvolumeclaim=\"$volume\"})\r\n  -\r\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"arangodb\", persistentvolumeclaim=\"$volume\"})\r\n)\r\n/\r\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"arangodb\", persistentvolumeclaim=\"$volume\"})\r\n* 100)\r\n"
    }
   ]
  },
  {
   "title": "Выделенная физическая память",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_server_statistics_physical_memory{service=~\"$service\"} / (1024^3)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Количество видимых ядер CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_server_statistics_cpu_cores{service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Процент времени, когда процессоры простаивали",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_idle_percent {service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Процент времени, kernel-mode",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_system_percent{service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Процент времени user-mode",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "arangodb_server_statistics_user_percent {service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Размер виртуальной памяти, используемой процессом",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_virtual_memory_size{service=~\"$service\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Число значительных отказов страниц (показатель может сопровождать замедление работы системы)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(arangodb_process_statistics_major_page_faults_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Относительный размер количества страниц, которые процесс имеет в реальной памяти по сравнению с системной памятью",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_resident_set_size_percent {service=~\"$service\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Количество подключений",
   "type": "timeseries",
   "description": "Количество клиентских подключений, открытых в данный момент (только соединения HTTP и HTTP/2, но не соединения VST)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections{service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Время жизни соединения(count/sec)",
   "type": "timeseries",
   "description": "Время между моментом установления соединения и моментом его закрытия (меньшие числа указывают на то, что нагрузка невелика)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_connection_time_count {service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "I/O time необходимое для ответа на запрос (avg per sec)",
   "type": "timeseries",
   "description": "Время, необходимое для ответа на запрос",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "rate(arangodb_client_connection_statistics_io_time_sum{service=~\"$service\"}[$__rate_interval]) / rate(arangodb_client_connection_statistics_io_time_count{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Количество запросов HTTP(по методам)",
   "type": "timeseries",
   "description": "Общее количество HTTP-запросов в разбивке по методам",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_http_get_requests_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "GET:{{pod}}"
    },
    {
     "expr": "rate(arangodb_http_request_statistics_http_post_requests_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "POST:{{pod}}"
    },
    {
     "expr": "rate(arangodb_http_request_statistics_http_put_requests_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "PUT:{{pod}}"
    },
    {
     "expr": "rate(arangodb_http_request_statistics_http_delete_requests_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "DELETE:{{pod}}"
    },
    {
     "expr": "rate(arangodb_http_request_statistics_http_patch_requests_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "PATCH:{{pod}}"
    }
   ]
  },
  {
   "title": "Количество запросов HTTP",
   "type": "timeseries",
   "description": "Общее количество HTTP-запросов",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(arangodb_http_request_statistics_total_requests_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Число потоков",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads{service=~\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Общее количество предупреждений",
   "type": "timeseries",
   "description": "Предупреждения системы  (не всегда свидетельствуют о ошибках, но порой интересные, например, насколько понимаю, среди них встречаются уведомления о медленных запросах)including startup warnings.\n\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(arangodb_logger_warnings_total{service=~\"$service\"}[3m])",
     "legendFormat": "{{pod}}:{{shortname}}"
    }
   ]
  },
  {
   "title": "Размер тела полученных VST-запросов",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(arangodb_request_body_size_vst_bucket{service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Общее количество ошибок",
   "type": "timeseries",
   "description": "Ошибки фатальные для какой-либо операции, но не для службы/сервиса в целом\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(arangodb_logger_errors_total{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{pod}}:{{shortname}}"
    }
   ]
  }
 ]
}