{
 "title": "UIK Service",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(uik_kafka_records_get_total, service)"
    }
   },
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Records (total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "uik_kafka_records_get_total{service=~\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors (total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(uik_kafka_records_errors_total{service=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZIP failed (total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(uik_zip_creation_failure_total{service=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZIP S3 failed (total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(uik_s3_object_upload_failure_total{service=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributive time creation (on time)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "uik_distributive_creation_seconds{service=~\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributive time creation (last)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uik_distributive_creation_seconds{service=~\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributive creation (5 qt)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, uik_distributive_creation_time_average{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Distributive creation (99 qt)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.99, uik_distributive_creation_time_average{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Distributive creation (1 qt)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.1, uik_distributive_creation_time_average{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Distributive creation (95 qt)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, uik_distributive_creation_time_average{service=~\"$service\"})"
    }
   ]
  }
 ]
}