{
 "title": "[PROD] NSI monitoring",
 "time": { "from": "2023-12-12T04:05:37.000Z", "to": "2023-12-12T07:17:50.000Z" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "General overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(nsi_query_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Request sync latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(nsi_query_sync_duration_seconds_sum) / sum(nsi_query_sync_duration_seconds_count)",
     "legendFormat": "Sync"
    },
    {
     "expr": "sum(nsi_query_async_duration_seconds_sum) / sum(nsi_query_async_duration_seconds_count)",
     "legendFormat": "Async"
    }
   ]
  },
  {
   "title": "Average structured search latency (WO inicidents)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(NSI_search_response_metric_seconds_sum{incident=\"false\", model=\"ADDRESS\"}) / sum(NSI_search_response_metric_seconds_count{incident=\"false\",model=\"ADDRESS\"}) ",
     "legendFormat": "Address"
    },
    {
     "expr": "sum(NSI_search_response_metric_seconds_sum{incident=\"false\", model=\"DICTIONARY\"}) / sum(NSI_search_response_metric_seconds_count{incident=\"false\",model=\"DICTIONARY\"}) ",
     "legendFormat": "Dictionary"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(NSI_search_request_metric_total)"
    }
   ]
  },
  {
   "title": "Incidents registered",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(register_incident_seconds_count) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Average incident resolving duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(NSI_search_response_metric_seconds_sum{incident=\"true\", model=\"ADDRESS\"}) / sum(NSI_search_response_metric_seconds_count{incident=\"true\",model=\"ADDRESS\"}) ",
     "legendFormat": "Address"
    },
    {
     "expr": "sum(NSI_search_response_metric_seconds_sum{incident=\"true\", model=\"DICTIONARY\"}) / sum(NSI_search_response_metric_seconds_count{incident=\"true\",model=\"DICTIONARY\"}) ",
     "legendFormat": "Dictionary"
    }
   ]
  },
  {
   "title": "Search methods overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(nsi_query_async_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Average request latency (per request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(nsi_query_async_duration_seconds_sum / nsi_query_async_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Average request count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(nsi_query_async_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Method request rate",
   "type": "timeseries",
   "description": "График запросов по методам",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (query) (rate(search_node_query_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (query) (delta(search_node_query_duration_seconds_count[$__range]))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Batch query count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (query) (delta(nsi_query_batch_async_duration_seconds_count[$__range]))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (query) (delta(search_node_query_duration_seconds_sum[$__range])))/(sum by (query) (delta(search_node_query_duration_seconds_count[$__range])))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Batch query latency",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (query) (delta(nsi_query_batch_async_duration_seconds_sum[$__range])) )/(sum by (query) (delta(nsi_query_batch_async_duration_seconds_count[$__range])))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Structured search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(NSI_search_request_metric_total)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Request latency (Dictionary)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.95, sum(NSI_search_response_metric_seconds_sum{incident=\"false\"}) by (model)) by (model)/ quantile(0.95, sum(NSI_search_response_metric_seconds_count{incident=\"false\"}) by (model)) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, sum(NSI_search_response_metric_seconds_sum{incident=\"false\"}) by (model)) by (model)/ quantile(0.95, sum(NSI_search_response_metric_seconds_count{incident=\"false\"}) by (model)) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Substitution rule count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(substitution_gauge) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Substitution operation count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nsi_query_substitution_seconds_count)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Substitution rate per a minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delta(nsi_query_substitution_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Substitution speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(nsi_query_substitution_seconds_sum)/sum(nsi_query_substitution_seconds_count)"
    }
   ]
  },
  {
   "title": "Incidents (Address)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(incident_gauge{status=\"created\"}) by (model)",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Registered incidents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(register_incident_seconds_count) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Commited incidents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(incident_commit_seconds_count) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Refine inicidents tasks count",
   "type": "timeseries",
   "description": "refine_address_incident_size",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(refine_address_incident_size)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Income request ticket count",
   "type": "timeseries",
   "description": "Количество записей в коллекции ticket (сервис micro-registry-watcher)  - количество запросов РУИП без ответа.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(income_request_ticket) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document index overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Indexed documents count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(index_master_storage_docs_count)"
    }
   ]
  },
  {
   "title": "Indexing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(delta(index_master_processed_addressees_counter_total [1m]))"
    }
   ]
  },
  {
   "title": "Delta cache size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(index_master_delta_size)" }
   ]
  },
  {
   "title": "Current status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "index_master_current_execution_state"
    }
   ]
  },
  {
   "title": "Current status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(index_master_current_execution_type)"
    }
   ]
  },
  {
   "title": "Fullname processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processing state",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "address_fullname_execution_status"
    }
   ]
  },
  {
   "title": "Address node processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 83 },
   "targets": [
    {
     "expr": "sum(address_fullname_processed_counter_total)"
    }
   ]
  },
  {
   "title": "Batch query latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(address_fullname_task_complete_counter_seconds_sum) / sum(address_fullname_task_complete_counter_seconds_count)"
    }
   ]
  },
  {
   "title": "Task completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(address_fullname_task_complete_counter_seconds_count)"
    }
   ]
  },
  {
   "title": "error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(address_fullname_error_counter_seconds_count)"
    }
   ]
  },
  {
   "title": "Fullname index repository count",
   "type": "timeseries",
   "description": "Количество объектов в коллекции fullnameindex",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(fullname_index_repository_size)"
    }
   ]
  }
 ]
}