{
 "title": "Jmeter | Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" },
   {
    "name": "JOB",
    "label": "JOB",
    "query": {
     "query": "label_values(jmeter_connect_time_count,job)"
    }
   },
   {
    "name": "TRANSACTION",
    "label": "TRANSACTION",
    "query": {
     "query": "label_values(jmeter_success_ratio_total,label)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests - $TRANSACTION",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_success_ratio_total{label =~ \"$TRANSACTION\", job =~ \"$JOB\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Requests - $TRANSACTION",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_success_ratio_failure{label =~ \"$TRANSACTION\", job =~ \"$JOB\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$JOB\"}"
    }
   ]
  },
  {
   "title": "Error Rate % - $TRANSACTION",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_success_ratio_failure{label =~ \"$TRANSACTION\", job =~ \"$JOB\"})/sum(jmeter_success_ratio_total{label =~ \"$TRANSACTION\", job =~ \"$JOB\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput - $TRANSACTION",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(jmeter_success_ratio_total{label =~ \"$TRANSACTION\", job =~ \"$JOB\"}[$__interval]))",
     "legendFormat": "Req / s"
    }
   ]
  },
  {
   "title": "Total Errors - $TRANSACTION",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delta(jmeter_success_ratio_failure{label=~\"$TRANSACTION\", job =~ \"$JOB\"}[$__interval]))",
     "legendFormat": "Num Of Errors"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\", job =~ \"$JOB\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Transactions Response Times (100th pct)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg((rate(jmeter_rt_summary_sum{job =~ \"$JOB\"}[$__interval]) / (rate(jmeter_rt_summary_count{job =~ \"$JOB\"}[$__interval]) > 0))) by (label)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput group by Sucsess and Error operations - $TRANSACTION",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(jmeter_success_ratio_success{label =~ \"$TRANSACTION\", job =~ \"$JOB\"}[$__interval]))",
     "legendFormat": "Sucsess - Req / s"
    },
    {
     "expr": "sum(rate(jmeter_success_ratio_failure{label =~ \"$TRANSACTION\", job =~ \"$JOB\"}[$__interval]))",
     "legendFormat": "Error - Req / s"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Errors - $TRANSACTION",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "jmeter_success_ratio_failure{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors By Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 34 },
   "targets": [
    {
     "expr": "sum by (label) (delta(jmeter_success_ratio_failure{label =~ \"$TRANSACTION\", job =~ \"$JOB\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jmeter JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory area [heap]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"$JOB\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\", job=\"$JOB\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"$JOB\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM heap - Used Memory By Pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job =~ \"$JOB\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$JOB\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}