annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
apiVersion: v2
appVersion: 1.7.0
description: A Helm chart for prometheus node-exporter
keywords:
- node-exporter
- prometheus
- exporter
maintainers:
- email: zalupa@gmail.com
  name: nikitaevdokimov
name: prometheus-node-exporter
type: application
version: 4.30.3
