{
 "title": "[PROD] Strimzi Kafka Mirror Maker 2",
 "time": { "from": "2023-12-11T04:05:37.000Z", "to": "2023-12-12T07:17:50.000Z" },
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "DATASOURCE", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kafka_connect_worker_connector_count{strimzi_io_kind=\"KafkaMirrorMaker2\"})"
    }
   },
   {
    "name": "strimzi_mirror_maker_cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(kafka_connect_worker_connector_count{namespace=\"$kubernetes_namespace\", strimzi_io_kind=\"KafkaMirrorMaker2\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Connectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_count{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total record rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_record_rate{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Incoming bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_incoming_byte_total{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_outgoing_byte_total{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}[1m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_task_count{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Total byte rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_byte_rate{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$kubernetes_namespace\",pod=~\"$strimzi_mirror_maker_cluster_name-mirrormaker2-.+\",container=\"$strimzi_mirror_maker_cluster_name-mirrormaker2\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Source Connector - Connect Outstanding Messages Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "msgs" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_source_task_source_record_active_count{connector=~\"\\\".*SourceConnector\\\"\"})",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Source Connector - Producer Available Buffer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_buffer_available_bytes{clientid=~\"\\\".*SourceConnector-[0-9]+\\\"\"})",
     "legendFormat": "{{clientid}}"
    }
   ]
  },
  {
   "title": "Source Connector - Average Offset Commit Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_connector_task_offset_commit_avg_time_ms{connector=~\"\\\".*SourceConnector\\\"\", task=~\"[0-9]+\"})/count(kafka_connect_connector_task_offset_commit_avg_time_ms{connector=~\"\\\".*SourceConnector\\\"\", task=~\"[0-9]+\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Record Age",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_record_age_ms{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_record_age_ms_avg{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_record_age_ms_min{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_record_age_ms_max{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    }
   ]
  },
  {
   "title": "Replication Latency",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_replication_latency_ms{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_replication_latency_ms_avg{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_replication_latency_ms_min{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorsourceconnector_replication_latency_ms_max{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (partition, topic)"
    }
   ]
  },
  {
   "title": "Offset Synchronization Latency",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (source, target)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_avg{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (source, target)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_min{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (source, target)"
    },
    {
     "expr": "sum(kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_max{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\"}) by (source, target)"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\",clientid!~\"consumer-mirrormaker2-.*\"}) by (topic, partition)",
     "legendFormat": "{{topic}} (partition: {{partition}})"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{strimzi_io_kind=~\"KafkaMirrorMaker2\",strimzi_io_cluster=\"$strimzi_mirror_maker_cluster_name\",clientid!~\"consumer-mirrormaker2-.*\"}) by (partition, topic)",
     "legendFormat": "{{topic}} (partition: {{partition}})"
    }
   ]
  }
 ]
}