apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foreman.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "foreman.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "foreman.renderTplValues" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
  {{- if .Values.global.commonAnnotations }}
    {{- include "foreman.renderTplValues" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "foreman.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "foreman.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      {{- include "foreman.pullSecrets" . | indent 6 }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ include "foreman.name" . }}
          image: {{ include "foreman.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config/00-config.yaml
              subPath: 00-config.yaml
              readOnly: true
            - name: sensitive-config
              mountPath: /app/config/01-config.yaml
              subPath: 01-config.yaml
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: [ "NET_RAW" ]
      volumes:
        - name: config
          configMap:
            name: {{ include "foreman.configMapName" . }}
        - name: sensitive-config
          secret:
            secretName: {{ include "foreman.secretName" . }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
