{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "foreman.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "foreman.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "foreman.renderTplValues" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "foreman.renderTplValues" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  01-config.yaml: |
    {{- if not (or .Values.config.auth.local.enabled .Values.config.auth.oidc.enabled .Values.config.cookies.key) }}
    {}
    {{- end }}
    {{- if .Values.config.cookies.key }}
    cookies:
      key: {{ .Values.config.cookies.key | quote }}
    {{- end -}}
    {{- if or .Values.config.auth.local.enabled .Values.config.auth.oidc.enabled }}
    auth:
      {{- if .Values.config.auth.local.enabled }}
      local:
        password: {{ include "foreman.localLoginPassword" . }}
      {{- end -}}
      {{- if .Values.config.auth.oidc.enabled }}
      oidc:
        clientId: {{ required "When configuring OIDC a clientId is required." .Values.config.auth.oidc.clientId | quote }}
        clientSecret: {{ required "When configuring OIDC a clientSecret is required." .Values.config.auth.oidc.clientSecret | quote }}
      {{- end }}
    {{- end }}
{{- end }}
